domain_path: /home/tam/Documents/RAAS/sw/vitis/platform5/export/platform5/sw/standalone_psu_cortexa53_0
app_src_dir: /home/tam/Documents/app/2025.2.1/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
