`ifndef RAAS_DEMO_VECTORS_SVH
`define RAAS_DEMO_VECTORS_SVH

// Generated by tools/export_raas_demo_data.py from the fixed-point MNIST references.
localparam int RAAS_DEMO_IMAGE_INDEX = 0;
localparam int RAAS_DEMO_EXPECTED_DIGIT = 5;
localparam int RAAS_DEMO_GOLDEN_DIGIT = 5;
`define RAAS_DEMO_IMAGE_MEM "../data/raas_demo_image.mem"
`define RAAS_DEMO_BIAS_MEM "../data/raas_demo_bias.mem"
`define RAAS_DEMO_WEIGHT_MEM "../data/raas_demo_weight.mem"
`define RAAS_DEMO_GOLDEN_MEM "../data/raas_demo_golden.mem"

`endif
