#!/usr/bin/env python3
"""
gen_lenet_data.py — Generate lenet_data.h for Vitis PS loader

Reads quantized weights from export_0.986/ and 1 MNIST test image,
packs them into C arrays for the PS app to prefill DDR.

Weight layout note:
  PyTorch stores Conv2d weights as [C_out, C_in, kH, kW] and Linear as [out, in].
  GEMM needs W[K_total, N] = W[C_in*kH*kW, C_out] for conv, W[in, out] for FC.
  So we TRANSPOSE all weight matrices here.

Usage:
    python3 gen_lenet_data.py [--image-index N] [--output PATH]
"""

import argparse
import struct
import os
import sys

def load_hex(path):
    """Load Q1.4.11 hex file → list of unsigned uint16."""
    values = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            values.append(int(line, 16))  # keep as unsigned 16-bit
    return values

def transpose_weights(w_flat, C_out, K_total):
    """Transpose [C_out, K_total] → [K_total, C_out], both as flat uint16 lists."""
    result = [0] * (K_total * C_out)
    for co in range(C_out):
        for k in range(K_total):
            result[k * C_out + co] = w_flat[co * K_total + k]
    return result

def pack_u16_to_u32(values):
    """Pack list of uint16 into list of uint32 (2 elements per word, little-endian)."""
    words = []
    for i in range(0, len(values), 2):
        lo = values[i]
        hi = values[i + 1] if i + 1 < len(values) else 0
        words.append((hi << 16) | lo)
    return words

def load_mnist_image(data_dir, index=0):
    """Load 1 image + label from raw MNIST test set."""
    img_path = os.path.join(data_dir, 't10k-images-idx3-ubyte')
    lbl_path = os.path.join(data_dir, 't10k-labels-idx1-ubyte')

    with open(img_path, 'rb') as f:
        f.seek(16 + index * 784)
        pixels = list(f.read(784))

    with open(lbl_path, 'rb') as f:
        f.seek(8 + index)
        label = f.read(1)[0]

    return pixels, label

def float_to_q1_4_11_u16(val):
    """Float → Q1.4.11 as unsigned uint16."""
    scaled = int(round(val * 2048))
    scaled = max(-32768, min(32767, scaled))
    if scaled < 0:
        scaled += 0x10000
    return scaled

def emit_u32_array(f, name, words, comment=""):
    """Write a uint32_t C array."""
    if comment:
        f.write(f"/* {comment} */\n")
    f.write(f"static const uint32_t {name}[{len(words)}] = {{\n")
    for i in range(0, len(words), 8):
        chunk = words[i:i+8]
        line = ", ".join(f"0x{w:08x}u" for w in chunk)
        f.write(f"    {line},\n")
    f.write(f"}};\n\n")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--image-index', type=int, default=0)
    parser.add_argument('--output', default=None)
    parser.add_argument('--export-dir', default=None)
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    model_dir = args.export_dir or os.path.join(
        repo_root, 'model', 'LeNet5-MNIST-PyTorch', 'models', 'export_0.986')
    mnist_dir = os.path.join(
        repo_root, 'model', 'LeNet5-MNIST-PyTorch', 'test', 'MNIST', 'raw')
    output_path = args.output or os.path.join(
        repo_root, 'sw', 'vitis', 'RAS_lenet', 'src', 'lenet_data.h')

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Load weights (PyTorch order)
    layers = [
        ('conv1', 6, 25),      # C_out=6,  K=1*5*5=25
        ('conv2', 16, 150),    # C_out=16, K=6*5*5=150
        ('fc1',   120, 256),   # out=120,  in=256
        ('fc2',   84, 120),    # out=84,   in=120
        ('fc3',   10, 84),     # out=10,   in=84
    ]

    weights = {}
    biases = {}
    for name, C_out, K_total in layers:
        w_raw = load_hex(os.path.join(model_dir, f'{name}.weight_q1_4_11.hex'))
        b_raw = load_hex(os.path.join(model_dir, f'{name}.bias_q1_4_11.hex'))
        assert len(w_raw) == C_out * K_total, f"{name} weight count mismatch: {len(w_raw)} != {C_out*K_total}"
        assert len(b_raw) == C_out, f"{name} bias count mismatch"
        # Transpose: [C_out, K_total] → [K_total, C_out]
        weights[name] = transpose_weights(w_raw, C_out, K_total)
        biases[name] = b_raw
        print(f"  {name}: weight {len(w_raw)} → transposed [{K_total}×{C_out}], bias {len(b_raw)}")

    # Load image
    pixels, label = load_mnist_image(mnist_dir, args.image_index)
    image_q = [float_to_q1_4_11_u16(p / 255.0) for p in pixels]
    print(f"  Image index={args.image_index}, label={label}")

    # Write header
    with open(output_path, 'w') as f:
        f.write("/* AUTO-GENERATED by tools/gen_lenet_data.py — do NOT edit */\n")
        f.write(f"/* Model: export_0.986, Image index: {args.image_index}, Label: {label} */\n\n")
        f.write("#ifndef LENET_DATA_H\n#define LENET_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")

        f.write(f"#define LENET_TEST_LABEL  {label}u\n\n")

        # Image
        emit_u32_array(f, "lenet_image", pack_u16_to_u32(image_q),
                       f"Input image 28x28, {len(image_q)} elements Q1.4.11")

        # Weights and biases
        for name, C_out, K_total in layers:
            emit_u32_array(f, f"lenet_{name}_weight",
                          pack_u16_to_u32(weights[name]),
                          f"{name} weight [{K_total}x{C_out}] transposed, {len(weights[name])} elements")
            emit_u32_array(f, f"lenet_{name}_bias",
                          pack_u16_to_u32(biases[name]),
                          f"{name} bias [{C_out}] elements")

        f.write("#endif /* LENET_DATA_H */\n")

    size = os.path.getsize(output_path)
    print(f"\nGenerated {output_path} ({size} bytes)")
    return 0

if __name__ == '__main__':
    sys.exit(main())
